### ISSUE TITLE
Error trying to upgrade to 3.0

### ISSUE THREAD

**Issue by sami1971** [sjchristi/skobbler-mono-bindings#14]
When running the fix_lib.rb script I get the following error. Any idea on why it is happening and how to fix it? This happens with all the other architectures as well if I run them manually.

> Making tmp working folder...
> Copying files..
> lipo -info SKMaps.framework/SKMaps > ./__fix_lib_tmp/lipo_info.txt
> Found the following architectures:
>   i386
>   x86_64
>   armv7
>   arm64
> Processing i386...
>   Splitting library...
>     cd ./__fix_lib_tmp && lipo SKMaps.a -thin i386 -output SKMaps-i386.a
>     cd ./__fix_lib_tmp/i386 && **ar -x ../SKMaps-i386.a**
> ar: ../SKMaps-i386.a: Inappropriate file type or format
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/file_utils.rb:53:in `block in create_shell_runner': Command failed with status (1): [    cd ./__fix_lib_tmp/i386 && ar -x ../SK...] (RuntimeError)
>   from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/file_utils.rb:45:in`call'
>   from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/file_utils.rb:45:in `sh'
>   from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/file_utils_ext.rb:40:in`sh'
>   from fix_lib.rb:47:in `block in <main>'
>   from fix_lib.rb:41:in`each'
>   from fix_lib.rb:41:in `<main>'

**Comment by srajs** [comment]
Hi sami,
when you open the solution in Xamarin studio you will get a folder "Native Reference".
add your new downloaded "SKmaps.framework" (v3.0.2) file to  "Native Reference" and remove SKMAps.a from the project.
then compile and use the dll.

for new SDK version its not required to run fix_lib.rb script.
Please let me know if there is any other problem.

Regards,
Sanath
