### ISSUE TITLE
iOS 64-bit support

### ISSUE THREAD

**Issue by sami1971** [sjchristi/skobbler-mono-bindings#3]
Any plans to refactor to Xamarin.iOS? I would suspect that would mean re-writing the sample app and remove MonoDialog UI?

**Comment by sjchristi** [comment]
I will work on this in the near future; I'm sorry but I'm traveling in patagonia right now and don't have much internet.  If anyone has time to do this, just send a pull request and I'll merge it.

thanks!
sam

**Comment by sjchristi** [comment]
ok, this is done -- please let me know if you notice any issues!

thanks,
sam
