### ISSUE TITLE
Upgrade to skobbler sdk v2.4

### ISSUE THREAD

**Issue by Dhanush-S** [sjchristi/skobbler-mono-bindings#4]
Hi,
Any plans on upgrading to new  2.4 sdk version?

Regards,
Dhanush

**Comment by sjchristi** [comment]
Yes I plan on upgrading to the new skobbler 2.4 sdk in a week or so -- I'm traveling right now and don't have great internet access -- sorry it won't be sooner.

**Comment by sjchristi** [comment]
ok, the new 2.4 SDK is in.  I've done very limited testing so please let me know if you run into issues!

thanks,
sam
