### ISSUE TITLE
Subtype: '{8FFB629D-F513-41CE-95D2-7ECE97B6EEEC}' is unsupported by this installation.

### ISSUE THREAD

**Issue by Thx1137** [sjchristi/skobbler-mono-bindings#5]
G'day,

Current Xamarin install failes with Subtype: '{8FFB629D-F513-41CE-95D2-7ECE97B6EEEC}' is unsupported by this installation when building SKMaps.

**Comment by sjchristi** [comment]
I'm sorry you are having trouble.  I just cleaned everything and rebuilt it
all and it all seems to be working ok.  Are you trying to build the debug
version or the release version -- for simulator or for device?  Maybe you
can send me the output from Xamarin studio?  Also, what version of Xamarin
studio are you using?  I'm on 5.8.3 (build 1).  Here is my Xamarin.iOS
version:

Xamarin.iOS
Version: 8.9.1.3

thanks,
sam

**Comment by Thx1137** [comment]
G’day,

I can’t load the project so can’t get to the compile stage. I am using VS 2013 with Xamarin Business edition.

I take it that you are building using Xamarin Studio on a mac? I will give that a go when I have time!

Regards,
  Steven.

**Comment by sjchristi** [comment]
Oh my, I'm sorry -- I only have xamarin studio on OSX, so I can't test in Visual Studio.  If you find out what the issue is with visual studio, please let me know, i'm happy to fix.
