### ISSUE TITLE
SKMaps Build Error

### ISSUE THREAD

**Issue by Dhanush-S** [sjchristi/skobbler-mono-bindings#7]
Hi,

I just downloaded the the copy of the repo and tried building the same. I get the following error :

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.ObjCBinding.Common.targets: Error: Error executing task CreateEmbeddedResources: Task does not have property "BundleResources" defined (SKMaps)

Am I missing some initializations?

I am using Xamarin Studio v5.9.1 in mac.Any help is greatly appreciated.

Thanks and Regards,
Dhanush

**Comment by sjchristi** [comment]
sorry about that -- looks like it was an issue introduced with xamarin 5.9; it should be fixed now.
