### ISSUE TITLE
Release Build Is Crashing

### ISSUE THREAD

**Issue by srajs** [sjchristi/skobbler-mono-bindings#8]
Hi,
I have trying to use SKMap in my project , So i have taken this project to check the bindings.
project works properly in "Debug" mode but when i try to execute it in "Release" mode the app crashes.

could you please help me out in this issue.

Note: I have pasted the stack trace from Device log below

 critical: Stacktrace:
 critical:   at <unknown> <0xffffffff>
 critical:   at (wrapper managed-to-native) ApiDefinition.Messaging.void_objc_msgSend_SKCoordinateRegion (intptr,intptr,SKMaps.SKCoordinateRegion) <0xffffffff>
 critical:   at SKMaps.SKMapView.set_VisibleRegion (SKMaps.SKCoordinateRegion) <0x0006f>
 critical:   at SKMapExample.ExOverlaysViewController.CreateMapView () <0x0085f>
 critical:   at SKMapExample.ExOverlaysViewController.ViewDidLoad () <0x00047>
 critical:   at (wrapper runtime-invoke) object.runtime_invoke_dynamic (intptr,intptr,intptr,intptr) <0xffffffff>
 critical:   at <unknown> <0xffffffff>
 critical:   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) <0xffffffff>
 critical:   at UIKit.UIApplication.Main (string[],intptr,intptr) <0x0002b>
 critical:   at UIKit.UIApplication.Main (string[],string,string) <0x000ab>
 critical:   at SKMapExample.Application.Main (string[]) <0x00023>
 critical:   at (wrapper runtime-invoke) object.runtime_invoke_dynamic (intptr,intptr,intptr,intptr) <0xffffffff>

Thanks in Advance,
Sanath

**Comment by sjchristi** [comment]
Sanath-

Is this happening on a device or on the simulator?  I will take a look!

thanks,
sam

**Comment by Dhanush-S** [comment]
Hi Sam,

Even I have observed the same behavior in device. This causes the app to crash on launch in release mode.

Regards,
Dhanush

**Comment by sjchristi** [comment]
Dhanush-

Could you shoot me an e-mail?  I'm trying to reproduce, and I've got a user hitting this same bug, but for some reason I'm not able to reproduce locally..  I'd like to try to figure this out!

thanks,
sam
sam.christiansen@gmail.com

**Comment by sjchristi** [comment]
Sanath-

I just pushed a new fix - can you try that out and see if it fixes it?

thanks,
sam
